#include "Character.h"
#include "Soldier.h"

bool isWalkable(const std::vector<size_t>& walkableGrid, const int gridWidth, const int gridHeight, Coord coord) {
  if (coord.x < 0 || coord.y < 0 || coord.x >= gridWidth ||
      coord.y >= gridHeight) {
    return false;
  }
  return walkableGrid[static_cast<std::size_t>(coord.y) * gridWidth + coord.x] != 0;
}


//TO REWORK : Generated by AI + Doesn't take potential grid cost (not implemented in walkableGrid too)
std::vector<Coord> Character::calculateMoveRange(const std::vector<size_t>& walkableGrid, const int gridWidth, const int gridHeight,
                     const std::vector<std::unique_ptr<Character>>& characters){
  this->getCoord();
  this->getStats().range;
  return {};

}



bool Soldier::workAI(const std::vector<size_t>& walkableGrid, const int gridWidth, const int gridHeight,
                     const std::vector<std::unique_ptr<Character>>& characters){
  this->usedAV = 1000.0f / this->getStats().speed;
  return true;
}