#include "Character.h"
#include "Soldier.h"
#include <queue>
#include <unordered_set>


bool isWalkable(const std::vector<size_t>& walkableGrid, const int gridWidth, const int gridHeight, Coord coord) {
  if (coord.x < 0 || coord.y < 0 || coord.x >= gridWidth ||
      coord.y >= gridHeight) {
    return false;
  }
  return walkableGrid[static_cast<std::size_t>(coord.y) * gridWidth + coord.x] != 0;
}


//TO REWORK : Generated by AI + Doesn't take potential grid cost (not implemented in walkableGrid too)
std::vector<Coord> Character::calculateMoveRange(const std::vector<size_t>& walkableGrid, const int gridWidth, const int gridHeight,
                     const std::vector<std::unique_ptr<Character>>& characters){

    const int maxRange = this->getStats().range;
    Coord start = this->coord;

    std::vector<Coord> result;

    auto isOccupied = [&](const Coord& c) -> bool {
        for (const auto& ch : characters) {
            if (ch && ch->getCoord().x == c.x && ch->getCoord().y == c.y) {
                return true;
            }
        }
        return false;
    };

    std::queue<std::pair<Coord, int>> q;
    std::unordered_set<int> visited;

    auto hashCoord = [&](const Coord& c) -> int {
        return c.y * gridWidth + c.x;
    };

    q.push({start, 0});
    visited.insert(hashCoord(start));

    const std::vector<Coord> directions = {
        {1, 0}, {-1, 0}, {0, 1}, {0, -1}
    };

    while (!q.empty()) {
        auto [current, dist] = q.front();
        q.pop();

        if (dist > 0) {
            result.push_back(current);
        }

        if (dist == maxRange) continue;

        for (const auto& dir : directions) {
            Coord next{current.x + dir.x, current.y + dir.y};

            int key = hashCoord(next);
            if (visited.count(key)) continue;

            if (!isWalkable(walkableGrid, gridWidth, gridHeight, next)) continue;
            if (isOccupied(next)) continue;

            visited.insert(key);
            q.push({next, dist + 1});
        }
    }

    return result;              
}



bool Soldier::workAI(const std::vector<size_t>& walkableGrid, const int gridWidth, const int gridHeight,
                     const std::vector<std::unique_ptr<Character>>& characters){
  this->usedAV = 1000.0f / this->getStats().speed;
  return true;
}